spring:
  application.name: bsfdv-app

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
        ddl-auto: create-drop

  data:
    rest:
      max-page-size: 50
  
  
server:
  servlet:
    context-path: /api/bsfdv